### ISSUE TITLE
Broken pipe

### ISSUE THREAD

**Issue by casic** [ffplayout/ffplayout-engine#48] opened 2020-04-12 11:35 UTC
Hi, 
I have installed , generated playlist and start the service. 
When i looked in log file  , there is i try to start   movie , but  finished with Broken pipe .
Any idea ???

**Comment by jb-alvarado** [comment] 2020-04-12 11:57
Hi,
can you post all 3 log files please?

**Comment by casic** [comment] 2020-04-12 15:02
ffplayout.log 
[2020-04-12 14:42:41,684] [INFO]  Using drawtext node, listening on address: tcp://127.0.0.1:5555
[2020-04-12 14:42:41,685] [INFO]  Open: /playlists/2020/04/2020-04-12.json
[2020-04-12 14:42:41,726] [DEBUG]  src_cmd: "['-ss', '3760.6089860000066', '-i', '/mnt/sda2/Documentary_movies/CLASSIC_MOVIES/hells house.mp4', '-filter_complex', '[0:v]scale=1024:576,fade=in:st=0:d=0.5[v];[v]null[logo]', '-filter_complex', '[0:a]anull,afade=in:st=0:d=0.5[a]', '-map', '[logo]', '-map', '[a]']"
[2020-04-12 14:42:41,726] [INFO]  Play: "/mnt/sda2/Documentary_movies/CLASSIC_MOVIES/hells house.mp4"
[2020-04-12 14:42:41,892] [ERROR]  Broken Pipe!


encoder.log
2020-04-12 13:55:24,454]  Unrecognized option 'crf'.
[2020-04-12 13:55:24,455]  Error splitting the argument list: Option not found
[2020-04-12 13:55:26,186]  Unrecognized option 'crf'.
[2020-04-12 13:55:26,186]  Error splitting the argument list: Option not found
[2020-04-12 13:55:27,684]  Unrecognized option 'crf'.


decoder.log
2020-04-12 13:55:25,012]  av_interleaved_write_frame(): Broken pipe
[2020-04-12 13:55:26,438]  av_interleaved_write_frame(): Broken pipe
[2020-04-12 13:55:26,440]      Last message repeated 1 times
[2020-04-12 13:55:26,440]  Error writing trailer of pipe:: Broken pipe
[2020-04-12 13:55:27,921]  av_interleaved_write_frame(): Broken pipe
[2020-04-12 13:55:27,923]      Last message repeated 1 times

**Comment by jb-alvarado** [comment] 2020-04-12 15:44
Ok, here is says: `Unrecognized option 'crf`, something is not right with the encoding settings.

Can you show me to the output settings? and also the console output from: `ffmpeg -V`

**Comment by casic** [comment] 2020-04-12 15:57
ffmpeg version 4.2.git Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: 
  libavutil      56. 42.102 / 56. 42.102
  libavcodec     58. 78.101 / 58. 78.101
  libavformat    58. 42.100 / 58. 42.100
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 77.101 /  7. 77.101
  libswscale      5.  6.101 /  5.  6.101
  libswresample   3.  6.100 /  3.  6.100

**Comment by casic** [comment] 2020-04-12 16:01
out by default  /etc/ffplayout/ffplayout.yml

**Comment by casic** [comment] 2020-04-12 16:01
out:
    preview: False
    service_name: "Live Stream"
    service_provider: "example.org"
    post_ffmpeg_param:
        c:v: "libx264"
        crf: "23"
        x264-params: "keyint=50:min-keyint=25:scenecut=-1"
        maxrate: "1300k"
        bufsize: "2600k"
        preset: "medium"
        profile:v: "Main"
        level: "3.1"
        c:a: "aac"
        ar: "44100"
        b:a: "128k"
        flags: +global_header
        f: "flv"
    out_addr: "rtmp://localhost/live/stream"

**Comment by jb-alvarado** [comment] 2020-04-12 16:02
I needed the output setting from ffplayout.yml to. But can it be, that you compiled ffmpeg without any external encoders? like libx264, etc.?

**Comment by casic** [comment] 2020-04-12 16:20
libx64 work.   I have transcoded  movie from  .mp4 to   .avi

**Comment by jb-alvarado** [comment] 2020-04-12 17:37
Hm, ok. Normally the `ffmpeg -version` should look like:
```
ffmpeg version git-2019-11-09-0f89a22 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 9 (GCC)
configuration: --disable-debug --disable-shared --disable-doc --enable-gpl --enable-version3 --enable-runtime-cpudetect --enable-avfilter --enable-zlib --enable-opengl --enable-fontconfig --enable-libfreetype --enable-libass --enable-libbluray --enable-libsrt --enable-libzimg --enable-libzmq --enable-libtwolame --enable-libmp3lame --enable-libopus --enable-libsoxr --enable-libaom --enable-libvpx --enable-libx264 --enable-libx265 --enable-nonfree --enable-libfdk-aac --enable-decklink --enable-openssl --enable-pic
libavutil      56. 35.101 / 56. 35.101
libavcodec     58. 60.100 / 58. 60.100
libavformat    58. 34.101 / 58. 34.101
libavdevice    58.  9.100 / 58.  9.100
libavfilter     7. 66.100 /  7. 66.100
libswscale      5.  6.100 /  5.  6.100
libswresample   3.  6.100 /  3.  6.100
libpostproc    55.  6.100 / 55.  6.100
```
there you see which encoders are included. You cloud try the ffplayout version from master, this one have a little modification in config file.

**Comment by casic** [comment] 2020-04-13 07:28
i have tried   master.   I think   libpostproc  is a problem but  i have include in configure.
How to test manualy ?
best regards

**Comment by jb-alvarado** [comment] 2020-04-13 07:56
Can it be that you use a older config then here the one from master? because there is a little modification.

the ffmpeg version you could test with: `ffmpeg -i input -c:v libx264 -crf 23 -c:a aac -f null -`

**Comment by casic** [comment] 2020-04-13 08:32
[2020-04-13 11:20:05,193]  Error splitting the argument list: Option not found
[2020-04-13 11:24:26,701]  [AVFilterGraph @ 0x55d36a632780] No such filter: 'zmq'
[2020-04-13 11:24:26,701]  Error reinitializing filters!
[2020-04-13 11:24:26,701]  Failed to inject frame into filter network: Invalid argument
[2020-04-13 11:24:26,702]  Error while processing the decoded data for stream #0:0
[2020-04-13 11:24:28,397]  [AVFilterGraph @ 0x55d50ccee080] No such filter: 'zmq'
[2020-04-13 11:24:28,397]  Error reinitializing filters!

**Comment by casic** [comment] 2020-04-13 08:33
I have preinstalled  FFMPeg 
now 
ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.16)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/4.2.2_1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags='-I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.1.jdk/Contents/Home/include -I/Library/Java/JavaVirtualMachines/adoptopenjdk-13.0.1.jdk/Contents/Home/include/darwin -fno-stack-check' --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libmp3lame --enable-libopus --enable-librubberband --enable-libsnappy --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
  libavutil      56. 31.100 / 56. 31.100
  libavcodec     58. 54.100 / 58. 54.100
  libavformat    58. 29.100 / 58. 29.100
  libavdevice    58.  8.100 / 58.  8.100
  libavfilter     7. 57.100 /  7. 57.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  5.100 /  5.  5.100
  libswresample   3.  5.100 /  3.  5.100
  libpostproc    55.  5.100 / 55.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

**Comment by jb-alvarado** [comment] 2020-04-13 09:49
You should disable text (`add_text: False`). When you want to use text overlay, you need to compile ffmpeg with libzmq.

Maybe I disable it by default.

**Comment by casic** [comment] 2020-04-13 11:37
Thanks.  Now it is work.  But when i  set  1920x1080       picture   is   mesh.

**Comment by jb-alvarado** [comment] 2020-04-13 11:41
What you mean with "picture is mesh"? The quality is not good? You need at least higher the:
```
maxrate: "1300k"
bufsize: "2600k"
```
in output settings. Maybe **maxrate** to 6000k and **bufsize** to 9000k. This you have to test a little bit.

**Comment by casic** [comment] 2020-04-13 11:48
Picture is in squares.   And  VLC  still get   1024x576   .    
I have change   /etc/ffplayout/ffplayout.yml  
width : 1920
height: 1080 

out:  
maxbiate: 6000k
bufsize :9000k

**Comment by eliysha** [comment] 2020-04-24 15:06
Hello 
I have the same issue but I don't get what was the fix 
Any clue please ?

**Comment by jb-alvarado** [comment] 2020-04-24 15:10
Hi,
when you update the scrip, but not the config, take a closer look to the `post_ffmpeg_param`. They have change a bit. Before it was an object, now it is a, space separated, string.

**Comment by eliysha** [comment] 2020-04-25 12:23
I got it :)
I've compiled ffmpeg with libx264, now it works fine :)
Thx
I have a lot of buffering during the live.
My upload bandwith is >100M, here is my settings : 
```
post_ffmpeg_param: >-
        -c:v libx264
        -crf 20
        -x264-params keyint=50:min-keyint=25:scenecut=-1
        -maxrate 4000k
        -bufsize 8000k
        -preset faster
        -profile:v Main
        -level 4
        -c:a aac
        -ar 44100
        -b:a 128k
        -flags +global_header
        -f flv
```

Do you have an idea ?

**Comment by jb-alvarado** [comment] 2020-04-25 18:43
What exactly you mean with buffering? I only see that you use crf 20, and when you have full HD resolution the maxrate and bufsize is to low. In my opinion 20 is to low. 23 is a good starting point, or maybe 22.

**Comment by eliysha** [comment] 2020-04-26 16:35
Ok thanks I have updated bitrate to 6000k and bufsize 9000K but I'm still noticing some temporary cuts (and reloading) on the player side.
But the most annoying is that my broadcast still stops and restarts for some files (and when it happens, it's already at the same time (for example it still cuts at 00:10:05 minutes of a video). 
In logs I can see this :

`/var/log/ffplayout/ffplayout.log`
```
[2020-04-26 16:19:32,605] [INFO]  Play: "/data/crctv/Medias/Retro2018.mp4"
[2020-04-26 16:24:12,260] [ERROR]  Broken Pipe! "[Errno 32] Broken pipe"
[2020-04-26 16:24:13,637] [INFO]  Open: /home/ubuntu/ffplayout-engine/playlists/2020/04/2020-04-26.json
```

`/var/log/ffplayout/encoder.log`
```
[2020-04-26 16:24:11,625]  av_interleaved_write_frame(): End of file
[2020-04-26 16:24:12,236]  Error writing trailer of rtmp://a.rtmp.youtube.com/live2/streamkey: End of file
```

`/var/log/ffplayout/decoder.log`
```
[2020-04-26 16:24:12,244]  av_interleaved_write_frame(): Broken pipe
[2020-04-26 16:24:12,249]  Error writing trailer of pipe:: Broken pipe
```
any idea please?

Thank you for your help

**Comment by jb-alvarado** [comment] 2020-04-26 17:23
Have you check if there is enough CPU power and ram?

**Comment by eliysha** [comment] 2020-04-26 17:56
I didn't check the ram but I have 32go (should be fine)
and for CPU it's around 50% of use

![image](https://user-images.githubusercontent.com/7480825/80315400-af8ac300-87f7-11ea-84ac-fecfde991b70.png)

I'm running the script on a server as I'm planning to run it remotely so running it on a server is the best way for testing
>you could also run the script on a local machine in preview mode to preclude any network or youtube issues.

**Comment by jb-alvarado** [comment] 2020-04-26 18:27
Can you test this [clips and playlist](https://github.com/ffplayout/test-clips)? At the moment is difficult to say, where is the problem. Could be the clips, or youtube, or something else.

**Comment by eliysha** [comment] 2020-04-26 18:31
Okay will do
Can you tell me what's the encoding settings for these clips files please ?
I could try to apply the same encoding settings on my original files for testing as well

**Comment by jb-alvarado** [comment] 2020-04-26 18:33
maybe you use first the default settings also a low resolution. And when this works, you can change to your settings.

**Comment by eliysha** [comment] 2020-04-28 14:27
After few days of testing : broadcasting in 720p works wells only one video is failing but I think there is an issue with the original file.

But in 1080p, the broadcast is failing randomly for some files (even after upgrading my server instance).

My thoughts : 
- mpeg2video is struggling with full HD videos ?
- what if I reduce the bitrate here `_pre_comp.v_bitrate = cfg['pre_compress']['width'] * 50` in utils.py ?
- is it possible to encode files (and store them physically) before the broadcast and change this parts to fetch and broadcast directly pre-encoded files ? 

```
with Popen([
                    'ffmpeg', '-v', _log.ff_level.lower(), '-hide_banner',
                    '-nostats'] + src_cmd + ff_pre_settings,
                        stdout=PIPE, stderr=PIPE) as _ff.decoder:

                    dec_err_thread = Thread(target=ffmpeg_stderr_reader,
                                            args=(_ff.decoder.stderr, True))
                    dec_err_thread.daemon = True
                    dec_err_thread.start()

                    while True:
                        buf = _ff.decoder.stdout.read(COPY_BUFSIZE)
                        if not buf:
                            break
                        _ff.encoder.stdin.write(buf)
```

**Comment by jb-alvarado** [comment] 2020-04-28 14:52
Thank you for sharing your test! I don't think that mpeg2video has a problem with HD, but I will start a test to. Normally we stream in a lower resolution, so there it runs very stable.

You can try to reduce the Bitrate, but would be strange if that makes the different. What you can try is, to higher the `thread_queue_size` in ffplayout.py maybe to 1024.

Are you working with an local storage or an remote? Is there always enough speed?

In the past I had a copy mode, in this case it could help. But for me it was a bit to sensitive. All files has to have exactly the same settings and same a/v length etc.

**Comment by eliysha** [comment] 2020-04-28 15:25
moreover I have more details regarding the broken pipe error

```
[2020-04-28 16:40:07,721]  [aac @ 0x55dc9c2ba880] Queue input is backward in time
[2020-04-28 16:40:07,734]  [flv @ 0x55dc9c2b8140] Non-monotonous DTS in output stream 0:1; previous: 1405629, current: 1405609; changing to 1405629. This may result in incorrect timestamps in the output file.
[2020-04-28 16:55:30,495]  av_interleaved_write_frame(): End of file
[2020-04-28 16:55:30,616]  [flv @ 0x55dc9c2b8140] Failed to update header with correct duration.
[2020-04-28 16:55:30,616]  [flv @ 0x55dc9c2b8140] Failed to update header with correct filesize.
[2020-04-28 16:55:30,616]  Error writing trailer of rtmp://ingest-va.streamspot.com/ingest?my_stream_key: End of file
[2020-04-28 16:55:30,616]  frame=58209 fps= 25 q=28.0 Lsize= 1186452kB time=00:38:48.46 bitrate=4174.2kbits/s speed=   1x
[2020-04-28 16:55:30,616]  video:1147002kB audio:36528kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.246892%
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] frame I:1165  Avg QP:18.45  size: 76300
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] frame P:18872 Avg QP:22.17  size: 32772
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] frame B:38172 Avg QP:23.24  size: 12263
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] consecutive B-frames:  8.4%  9.4%  9.8% 72.5%
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] mb I  I16..4: 55.5%  0.0% 44.5%
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] mb P  I16..4: 31.7%  0.0% 11.2%  P16..4: 23.3%  9.5%  3.2%  0.0%  0.0%    skip:21.2%
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] mb B  I16..4:  6.4%  0.0%  1.3%  B16..8: 20.6%  5.7%  0.4%  direct:10.3%  skip:55.4%  L0:45.4% L1:46.0% BI: 8.6%
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] coded y,uvDC,uvAC intra: 23.2% 49.7% 7.4% inter: 5.4% 18.2% 0.2%
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] i16 v,h,dc,p: 48% 22% 17% 13%
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] i4 v,h,dc,ddl,ddr,vr,hd,vl,hu: 33% 19% 20%  5%  5%  5%  4%  5%  3%
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] i8c dc,h,v,p: 47% 20% 27%  7%
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] Weighted P-Frames: Y:2.1% UV:1.3%
[2020-04-28 16:55:30,618]  [libx264 @ 0x55dc9c2d1140] kb/s:4038.65
[2020-04-28 16:55:30,623]  [aac @ 0x55dc9c2ba880] Qavg: 205.332
[2020-04-28 16:55:30,623]  Conversion failed!
```

**Comment by eliysha** [comment] 2020-04-28 15:28
I'm working on local storage
My files haven't the same settings and length

**Comment by jb-alvarado** [comment] 2020-04-28 15:55
My first impression is, that it gets not fast enough new input. Maybe this can be fixed by a high `thread_queue_size`. But for saying more, I need to reproduce this issue.

**Comment by jb-alvarado** [comment] 2020-05-04 12:12
My test runs now 4 days without any error. It look like that your issue is not related to ffplayout. Can you reproduce the error with specific files?

**Comment by eliysha** [comment] 2020-05-07 11:12
Please can you share config you're using ?

**Comment by jb-alvarado** [comment] 2020-05-07 11:51
I change only the resolution:

```yaml
pre_compress:
    width: 1920
    height: 1080
```

And the output settings:

```yaml
    post_ffmpeg_param: >-
        -c:v libx264
        -crf 23
        -x264-params keyint=50:min-keyint=25:scenecut=-1
        -maxrate 6000k
        -bufsize 9600k
        -preset superfast
        -profile:v Main
        -level 3.1
        -c:a aac
        -ar 44100
        -b:a 128k
        -flags +global_header
        -f flv
```

**Comment by Euidem** [comment] 2020-05-10 16:18
Hi @jb-alvarado  How can i reach you? I just discovered ffplayout and it is exactly what i have been searching for. I will love to reach out

**Comment by jb-alvarado** [comment] 2020-05-10 18:45
Hi Euidem, I made an announcement - I think you should get there my email address.

**Comment by jb-alvarado** [comment] 2020-06-01 19:29
I close here, because of no activity. Please open a new one when something is happen.

**Closed by jb-alvarado** 2020-06-01 19:29 UTC

**Comment by navneetpal-git** [comment] 2022-03-04 14:49
Hi All,

I have installed the project successfully all things are fine but when I am trying to execute the code with the below command getting an error with a look into the matter and suggest to me how to fix this issue.
CMD : ./ffplayout.py -l none -p ~/opt/ffplayout_engine/playlist.json -s now -t none -o desktop
Response : ~/opt/ffplayout_engine# ./ffplayout.py -l none -p ~/opt/ffplayout_engine/playlist.json -s now -t none -o desktop
[2022-03-04 14:36:54,401][WARNING]  ffmpeg contains no libfdk-aac! No high quality aac...
[2022-03-04 14:36:54,404][DEBUG]    Encoder CMD: "ffplay -hide_banner -nostats -v level+error -i pipe:0"
[2022-03-04 14:36:54,634][INFO]     Open: /root/opt/ffplayout_engine/playlist.json
[2022-03-04 14:36:54,641][DEBUG]    List init
[2022-03-04 14:36:54,850][INFO]     Play for 1200.16 seconds: media/White.mp4
[2022-03-04 14:36:54,850][DEBUG]    Decoder CMD: "ffmpeg -v level+error -hide_banner -nostats -i media/White.mp4 -filter_complex [0:v]tpad=stop_mode=add:stop_duration=0.16200000000003456[v];movie=docs/logo.png,loop=loop=-1:size=1:start=0,format=rgba,colorchannelmixer=aa=0.7[l];[v][l]overlay=W-w-12:12:shortest=1[vout1] -filter_complex [0:a]anull,apad=whole_dur=1200.162[aout1] -map [vout1] -map [aout1] -pix_fmt yuv420p -r 25 -c:v mpeg2video -g 1 -b:v 58982.4k -minrate 58982.4k -maxrate 58982.4k -bufsize 29491.2k -c:a s302m -strict -2 -ar 48000 -ac 2 -f mpegts -"
[2022-03-04 14:36:54,969][ERROR]    [Decoder] av_interleaved_write_frame(): Broken pipe
[2022-03-04 14:36:54,980][ERROR]    Broken Pipe!
[2022-03-04 14:36:54,980][DEBUG]    -------------------------------------------------------------------------------
[2022-03-04 14:36:54,980][DEBUG]    error: "[Errno 32] Broken pipe"
[2022-03-04 14:36:54,981][DEBUG]    delta: "0"
[2022-03-04 14:36:54,981][DEBUG]    node: "{'in': 0, 'out': 1200.162, 'duration': 1200.162, 'source': 'media/White.mp4', 'seek': 0, 'begin': 52614.266761, 'number': 1, 'probe': <ffplayout.utils.MediaProbe object at 0x7f51c932f668>, 'src_cmd': ['-i', 'media/White.mp4'], 'filter': ['-filter_complex', '[0:v]tpad=stop_mode=add:stop_duration=0.16200000000003456[v];movie=docs/logo.png,loop=loop=-1:size=1:start=0,format=rgba,colorchannelmixer=aa=0.7[l];[v][l]overlay=W-w-12:12:shortest=1[vout1]', '-filter_complex', '[0:a]anull,apad=whole_dur=1200.162[aout1]', '-map', '[vout1]', '-map', '[aout1]']}"
[2022-03-04 14:36:54,981][DEBUG]    dec_cmd: "['ffmpeg', '-v', 'level+error', '-hide_banner', '-nostats', '-i', 'media/White.mp4', '-filter_complex', '[0:v]tpad=stop_mode=add:stop_duration=0.16200000000003456[v];movie=docs/logo.png,loop=loop=-1:size=1:start=0,format=rgba,colorchannelmixer=aa=0.7[l];[v][l]overlay=W-w-12:12:shortest=1[vout1]', '-filter_complex', '[0:a]anull,apad=whole_dur=1200.162[aout1]', '-map', '[vout1]', '-map', '[aout1]', '-pix_fmt', 'yuv420p', '-r', '25', '-c:v', 'mpeg2video', '-g', '1', '-b:v', '58982.4k', '-minrate', '58982.4k', '-maxrate', '58982.4k', '-bufsize', '29491.2k', '-c:a', 's302m', '-strict', '-2', '-ar', '48000', '-ac', '2', '-f', 'mpegts', '-']"
[2022-03-04 14:36:54,981][DEBUG]    -------------------------------------------------------------------------------

**Comment by jb-alvarado** [comment] 2022-03-05 21:15
Hello, 

Can you give some informations about your operating system? And when you are on a desktop system, can you try to run this command as a normal user?

**/root/opt/ffplayout_engine/** is also not a good install path. When you run only on desktop mode, you can install it in your home. Or make it more generic under **/opt/ffplayout_engine/**.
